Add workflows
* .github/build: add github action file to compile binary

Signed-off-by: 3picF4iL <haskypl1@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,26 +1,44 @@
+name: Compile Python code for Zortech
+
+on:
+  push:
+    branches:
+      - master
+  pull_request:
+    branches:
+      - master
+
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
+    env:
+      FILENAME: "ZORTECH"
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+    - uses: actions/checkout@v2
 
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
-        python-version: '3.9.1'
+        python-version: '3.9'
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install pyinstaller
+    - name: Install PyInstaller
+      run: pip install pyinstaller
 
     - name: Build executable
-      run: pyinstaller --onefile main.py
+      run: pyinstaller --onefile --name ${{ env.FILENAME }} main.py
+      shell: cmd
 
-    - name: Upload Artifacts
+    - name: Check if executable was created
+      run: |
+        if not exist .\dist\${{ env.FILENAME }}.exe (
+          echo "Executable file not found."
+          exit 1
+        )
+      shell: cmd
+
+    - name: Upload executable
       uses: actions/upload-artifact@v2
       with:
-        name: executable
-        path: dist/*
+        name: windows-executable
+        path: dist/${{ env.FILENAME }}.exe
